In [8]:
import pandas as pd

In [26]:
csv_path=("new_york_listings_2024.csv")
df=pd.read_csv(csv_path)
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
0,1312228,Rental unit in Brooklyn · ★5.0 · 1 bedroom,7130382,Walter,Brooklyn,Clinton Hill,40.683710,-73.964610,Private room,55.0,30,3,2015-12-20,0.03,1,0,0,No License,5.0,1,1,Not specified
1,45277537,Rental unit in New York · ★4.67 · 2 bedrooms ·...,51501835,Jeniffer,Manhattan,Hell's Kitchen,40.766610,-73.988100,Entire home/apt,144.0,30,9,2023-05-01,0.24,139,364,2,No License,4.67,2,1,1
2,971353993633883038,Rental unit in New York · ★4.17 · 1 bedroom · ...,528871354,Joshua,Manhattan,Chelsea,40.750764,-73.994605,Entire home/apt,187.0,2,6,2023-12-18,1.67,1,343,6,Exempt,4.17,1,2,1
3,3857863,Rental unit in New York · ★4.64 · 1 bedroom · ...,19902271,John And Catherine,Manhattan,Washington Heights,40.835600,-73.942500,Private room,120.0,30,156,2023-09-17,1.38,2,363,12,No License,4.64,1,1,1
4,40896611,Condo in New York · ★4.91 · Studio · 1 bed · 1...,61391963,Stay With Vibe,Manhattan,Murray Hill,40.751120,-73.978600,Entire home/apt,85.0,30,11,2023-12-03,0.24,133,335,3,No License,4.91,Studio,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20753,24736896,Rental unit in New York · ★4.75 · 1 bedroom · ...,186680487,Henry D,Manhattan,Lower East Side,40.711380,-73.991560,Private room,45.0,30,124,2023-09-29,1.81,1,157,12,No License,4.75,1,1,1
20754,2835711,Rental unit in New York · ★4.46 · 1 bedroom · ...,3237504,Aspen,Manhattan,Greenwich Village,40.730580,-74.000700,Entire home/apt,105.0,30,56,2023-07-01,0.48,1,0,1,No License,4.46,1,2,1
20755,51825274,Rental unit in New York · ★4.93 · 1 bedroom · ...,304317395,Jeff,Manhattan,Hell's Kitchen,40.757350,-73.993430,Entire home/apt,299.0,30,60,2023-12-08,2.09,1,0,27,No License,4.93,1,1,1
20756,782661008019550832,Rental unit in New York · ★5.0 · 1 bedroom · 1...,163083101,Marissa,Manhattan,Chinatown,40.713750,-73.991470,Entire home/apt,115.0,30,7,2023-09-17,0.91,1,363,7,No License,5.0,1,1,1
20757,566029911248687183,Rental unit in Queens · ★4.89 · 1 bedroom · 1 ...,93827372,Glenroy,Queens,Rosedale,40.658874,-73.728651,Private room,102.0,1,63,2023-12-10,4.50,1,0,62,OSE-STRREG-0000513,4.89,1,1,1

In [23]:

df.shape

(20758, 22)

In [24]:
df.info

<bound method DataFrame.info of                        id                                               name  \
0                 1312228         Rental unit in Brooklyn · ★5.0 · 1 bedroom
1                45277537  Rental unit in New York · ★4.67 · 2 bedrooms ·...
2      971353993633883038  Rental unit in New York · ★4.17 · 1 bedroom · ...
3                 3857863  Rental unit in New York · ★4.64 · 1 bedroom · ...
4                40896611  Condo in New York · ★4.91 · Studio · 1 bed · 1...
...                   ...                                                ...
20753            24736896  Rental unit in New York · ★4.75 · 1 bedroom · ...
20754             2835711  Rental unit in New York · ★4.46 · 1 bedroom · ...
20755            51825274  Rental unit in New York · ★4.93 · 1 bedroom · ...
20756  782661008019550832  Rental unit in New York · ★5.0 · 1 bedroom · 1...
20757  566029911248687183  Rental unit in Queens · ★4.89 · 1 bedroom · 1 ...

         host_id           host_name neighbourhood_group       neighbourhood  \
0        7130382              Walter            Brooklyn        Clinton Hill
1       51501835            Jeniffer           Manhattan      Hell's Kitchen
2      528871354              Joshua           Manhattan             Chelsea
3       19902271  John And Catherine           Manhattan  Washington Heights
4       61391963      Stay With Vibe           Manhattan         Murray Hill
...          ...                 ...                 ...                 ...
20753  186680487             Henry D           Manhattan     Lower East Side
20754    3237504               Aspen           Manhattan   Greenwich Village
20755  304317395                Jeff           Manhattan      Hell's Kitchen
20756  163083101             Marissa           Manhattan           Chinatown
20757   93827372             Glenroy              Queens            Rosedale

        latitude  longitude        room_type  price  ...  last_review  \
0      40.683710 -73.964610     Private room   55.0  ...   2015-12-20
1      40.766610 -73.988100  Entire home/apt  144.0  ...   2023-05-01
2      40.750764 -73.994605  Entire home/apt  187.0  ...   2023-12-18
3      40.835600 -73.942500     Private room  120.0  ...   2023-09-17
4      40.751120 -73.978600  Entire home/apt   85.0  ...   2023-12-03
...          ...        ...              ...    ...  ...          ...
20753  40.711380 -73.991560     Private room   45.0  ...   2023-09-29
20754  40.730580 -74.000700  Entire home/apt  105.0  ...   2023-07-01
20755  40.757350 -73.993430  Entire home/apt  299.0  ...   2023-12-08
20756  40.713750 -73.991470  Entire home/apt  115.0  ...   2023-09-17
20757  40.658874 -73.728651     Private room  102.0  ...   2023-12-10

       reviews_per_month calculated_host_listings_count  availability_365  \
0                   0.03                              1                 0
1                   0.24                            139               364
2                   1.67                              1               343
3                   1.38                              2               363
4                   0.24                            133               335
...                  ...                            ...               ...
20753               1.81                              1               157
20754               0.48                              1                 0
20755               2.09                              1                 0
20756               0.91                              1               363
20757               4.50                              1                 0

       number_of_reviews_ltm             license  rating bedrooms beds  \
0                          0          No License    5.0         1    1
1                          2          No License   4.67         2    1
2                          6              Exempt   4.17         1    2
3                         12          No License   4.64         1    1
4                          3          No License   4.91    Studio    1
...                      ...                 ...     ...      ...  ...
20753                     12          No License   4.75         1    1
20754                      1          No License   4.46         1    2
20755                     27          No License   4.93         1    1
20756                      7          No License    5.0         1    1
20757                     62  OSE-STRREG-0000513   4.89         1    1

               baths
0      Not specified
1                  1
2                  1
3                  1
4                  1
...              ...
20753              1
20754              1
20755              1
20756              1
20757              1

[20758 rows x 22 columns]>

In [25]:
pd.set_option('display.max_columns',85)

In [27]:
schema_df=pd.read_csv(csv_path)

In [28]:
schema_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license,rating,bedrooms,beds,baths
0,1312228,Rental unit in Brooklyn · ★5.0 · 1 bedroom,7130382,Walter,Brooklyn,Clinton Hill,40.683710,-73.964610,Private room,55.0,30,3,2015-12-20,0.03,1,0,0,No License,5.0,1,1,Not specified
1,45277537,Rental unit in New York · ★4.67 · 2 bedrooms ·...,51501835,Jeniffer,Manhattan,Hell's Kitchen,40.766610,-73.988100,Entire home/apt,144.0,30,9,2023-05-01,0.24,139,364,2,No License,4.67,2,1,1
2,971353993633883038,Rental unit in New York · ★4.17 · 1 bedroom · ...,528871354,Joshua,Manhattan,Chelsea,40.750764,-73.994605,Entire home/apt,187.0,2,6,2023-12-18,1.67,1,343,6,Exempt,4.17,1,2,1
3,3857863,Rental unit in New York · ★4.64 · 1 bedroom · ...,19902271,John And Catherine,Manhattan,Washington Heights,40.835600,-73.942500,Private room,120.0,30,156,2023-09-17,1.38,2,363,12,No License,4.64,1,1,1
4,40896611,Condo in New York · ★4.91 · Studio · 1 bed · 1...,61391963,Stay With Vibe,Manhattan,Murray Hill,40.751120,-73.978600,Entire home/apt,85.0,30,11,2023-12-03,0.24,133,335,3,No License,4.91,Studio,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20753,24736896,Rental unit in New York · ★4.75 · 1 bedroom · ...,186680487,Henry D,Manhattan,Lower East Side,40.711380,-73.991560,Private room,45.0,30,124,2023-09-29,1.81,1,157,12,No License,4.75,1,1,1
20754,2835711,Rental unit in New York · ★4.46 · 1 bedroom · ...,3237504,Aspen,Manhattan,Greenwich Village,40.730580,-74.000700,Entire home/apt,105.0,30,56,2023-07-01,0.48,1,0,1,No License,4.46,1,2,1
20755,51825274,Rental unit in New York · ★4.93 · 1 bedroom · ...,304317395,Jeff,Manhattan,Hell's Kitchen,40.757350,-73.993430,Entire home/apt,299.0,30,60,2023-12-08,2.09,1,0,27,No License,4.93,1,1,1
20756,782661008019550832,Rental unit in New York · ★5.0 · 1 bedroom · 1...,163083101,Marissa,Manhattan,Chinatown,40.713750,-73.991470,Entire home/apt,115.0,30,7,2023-09-17,0.91,1,363,7,No License,5.0,1,1,1
20757,566029911248687183,Rental unit in Queens · ★4.89 · 1 bedroom · 1 ...,93827372,Glenroy,Queens,Rosedale,40.658874,-73.728651,Private room,102.0,1,63,2023-12-10,4.50,1,0,62,OSE-STRREG-0000513,4.89,1,1,1

In [30]:
df['minimum_nights'].unique

<bound method Series.unique of 0        30
1        30
2         2
3        30
4        30
         ..
20753    30
20754    30
20755    30
20756    30
20757     1
Name: minimum_nights, Length: 20758, dtype: int64>

In [32]:
df1=df['minimum_nights']>=30

0         True
1         True
2        False
3         True
4         True
         ...
20753     True
20754     True
20755     True
20756     True
20757    False
Name: minimum_nights, Length: 20758, dtype: bool

In [33]:
df1

0         True
1         True
2        False
3         True
4         True
         ...
20753     True
20754     True
20755     True
20756     True
20757    False
Name: minimum_nights, Length: 20758, dtype: bool

In [ ]:
df1. to_csv('minimum_nights.csv')